##### Data Reading Tasks:

In [2]:
import pandas as pd
# Read the dataset from a CSV file into a pandas DataFrame
df = pd.read_csv('sales.csv')
df

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

In [ ]:
# Display the first 8 rows and check the basic structure of the dataset using .info()
x = df.head(8)
x

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
5,6,2024-07-07,West,Laptop,Electronics,New,8,1480,0.01,11721.60
6,7,2024-01-21,East,Mouse,Accessories,Returning,6,137,0.27,600.06
7,8,2024-04-12,West,Phone,Accessories,Returning,5,1117,0.26,4132.90

In [ ]:
x.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       8 non-null      int64
 1   date           8 non-null      str
 2   region         8 non-null      str
 3   product        8 non-null      str
 4   category       8 non-null      str
 5   customer_type  8 non-null      str
 6   quantity       8 non-null      int64
 7   price          8 non-null      int64
 8   discount       8 non-null      float64
 9   sales          8 non-null      float64
dtypes: float64(2), int64(3), str(5)
memory usage: 772.0 bytes

In [ ]:
# Get statistical summary of numerical columns using .describe()
x.describe()

       order_id  quantity      price  discount         sales
count   8.00000   8.00000     8.0000  8.000000      8.000000
mean    4.50000   5.25000   614.3750  0.151250   3220.388750
std     2.44949   2.60494   456.9373  0.094633   3768.492671
min     1.00000   1.00000   137.0000  0.010000    429.680000
25%     2.75000   4.25000   314.5000  0.090000    560.382500
50%     4.50000   5.50000   498.5000  0.135000   2071.160000
75%     6.25000   7.25000   721.7500  0.230000   4173.475000
max     8.00000   8.00000  1480.0000  0.270000  11721.600000

In [ ]:
# Check column names and rename any columns for better readability and rename.
df.columns

Index(['order_id', 'date', 'region', 'product', 'category', 'customer_type',
       'quantity', 'price', 'discount', 'sales'],
      dtype='str')

In [ ]:
df.rename(columns = {'order_id' : 'OrderID'})

,OrderID,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

### Data Cleaning Tasks:

In [12]:
# Check for missing values in each column and handle them appropriately
df.isnull().sum()

order_id         0
date             0
region           0
product          0
category         0
customer_type    0
quantity         0
price            0
discount         0
sales            0
dtype: int64

In [13]:
# Check for duplicate rows and remove any duplicates if found
df.duplicated().sum()

np.int64(0)

In [7]:
# Convert 'date' column to datetime format
df['date'] = pd.to_datetime(df['date'])
df

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

In [8]:
# Check data types of all columns and convert if necessary
df.dtypes

order_id                  int64
date             datetime64[us]
region                      str
product                     str
category                    str
customer_type               str
quantity                  int64
price                     int64
discount                float64
sales                   float64
dtype: object

In [ ]:
df = df.astype({'price' : float})
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       500 non-null    int64
 1   date           500 non-null    datetime64[us]
 2   region         500 non-null    str
 3   product        500 non-null    str
 4   category       500 non-null    str
 5   customer_type  500 non-null    str
 6   quantity       500 non-null    int64
 7   price          500 non-null    float64
 8   discount       500 non-null    float64
 9   sales          500 non-null    float64
dtypes: datetime64[us](1), float64(3), int64(2), str(4)
memory usage: 39.2 KB

In [ ]:
# Standardize 'region' values
df['region'] = df['region'].str.strip().str.title()
print(df['region'])

0       East
1      South
2      North
3       West
4       West
       ...
495    South
496    North
497    South
498    North
499    North
Name: region, Length: 500, dtype: str

### Data Analysis Tasks:

In [ ]:
# Calculate total sales by region and find which region has the highest sales
df.groupby('region')['sales'].sum()

region
East     422023.71
North    509052.69
South    362158.72
West     373294.66
Name: sales, dtype: float64

In [9]:
# Find the average discount given for each product category
Discount = df.groupby('category')['discount'].mean()
Discount

category
Accessories    0.151111
Electronics    0.142744
Name: discount, dtype: float64

In [ ]:
# Analyze customer ratings - calculate average rating by customer type (New vs Returning)
df.groupby('customer_type')['discount'].mean().round(2)

customer_type
New          0.14
Returning    0.15
Name: discount, dtype: float64

In [ ]:
# Find top 5 products by quantity sold
df.groupby('product')['quantity'].sum().sort_values(ascending=False).head(5)

product
Mouse       481
Laptop      449
Tablet      411
Keyboard    390
Phone       383
Name: quantity, dtype: int64

In [ ]:
# Calculate monthly sales trend by extracting month from date column
df.groupby(df['date'].dt.to_period('M'))['sales'].sum()

date
2024-01     98673.77
2024-02    131625.24
2024-03     70335.46
2024-04    150967.04
2024-05    176939.29
2024-06    155607.27
2024-07    128419.96
2024-08    194347.39
2024-09    157999.69
2024-10    131809.83
2024-11    118704.40
2024-12    151100.44
Freq: M, Name: sales, dtype: float64

In [11]:
# Analyze discount impact on sales - compare average sales with and without discount
discount_impact = df.groupby(df['discount'] > 0)['sales'].agg(['mean', 'count', 'sum']).round(3)
discount = df.groupby(df['discount'] > 0)['sales'].agg
discount_impact.index = ['No Discount', 'With Discount']
print(discount_impact)

                   mean  count         sum
No Discount    4165.846     13    54156.00
With Discount  3310.829    487  1612373.78

In [ ]:
# Find the most profitable product (highest total sales amount)
df.groupby('product')['sales'].sum().sort_values(ascending=False)

product
Laptop      317281.14
Mouse       299401.20
Monitor     281509.14
Tablet      262582.76
Keyboard    260675.81
Phone       245079.73
Name: sales, dtype: float64

In [ ]:
# Analyze customer behavior - compare purchase patterns between New and Returning customers
df.groupby('customer_type')[['quantity', 'sales', 'discount']].mean().round(3)

               quantity     sales  discount
customer_type
New               4.937  3321.914     0.141
Returning         4.996  3343.266     0.152